# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

params_cross_section = {
    'two_lanes_default': {
        'sides': ['left', 'left', 'center', 'right', 'right'],
        'widths': [0.20, 3.75, 0.0, 3.75, 0.20],
        'widths_change': ['none', 'none', 'none', 'none', 'none'],
        'types': ['border', 'driving', 'center', 'driving', 'border'],
        'road_mark_types': ['none', 'solid', 'broken', 'solid', 'none'],
        'road_mark_weights': ['none', 'standard', 'standard', 'standard', 'none'],
        'road_mark_widths': [0.0, 0.12, 0.12, 0.12, 0.0],
        'road_mark_colors': ['none', 'white', 'white', 'white', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 4,
    },
    # Typical German road cross sections
    # See:
    #   https://de.wikipedia.org/wiki/Richtlinien_f%C3%BCr_die_Anlage_von_Stra%C3%9Fen_%E2%80%93_Querschnitt
    #   https://de.wikipedia.org/wiki/Richtlinien_f%C3%BCr_die_Anlage_von_Autobahnen
    #   https://de.wikipedia.org/wiki/Entwurfsklasse
    #   https://www.beton.wiki/index.php?title=Regelquerschnitt_im_Stra%C3%9Fenbau
    #   https://www.vsvi-mv.de/fileadmin/Medienpool/Seminarunterlagen/Seminare_2012/Vortrag_1_-_neue_RAL_Frau_Vetters.pdf
    #   https://dsgs.de/leitfaden-fahrbahnmarkierung1.html
    #
    'ekl4_rq9': {
        'sides': ['left', 'left', 'center', 'right', 'right', 'right'],
        'widths': [1.5, 0.5, 0.0, 3.5, 0.5, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'border', 'center', 'driving', 'border', 'shoulder'],
        'road_mark_types': ['none', 'none', 'broken', 'broken', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'standard', 'standard', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.12, 0.12, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'white', 'white', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 5,
    },
    'ekl3_rq11': {
        'sides': ['left', 'left', 'left', 'center', 'right', 'right', 'right'],
        'widths': [1.5, 0.50, 3.5, 0.0, 3.5, 0.50, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'border', 'driving', 'center', 'driving', 'border', 'shoulder'],
        'road_mark_types': ['none', 'none', 'solid', 'broken', 'solid', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'standard', 'standard', 'standard', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.12, 0.12, 0.12, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'white', 'white', 'white', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 6,
    },
    'eka1_rq31': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 14,
    },
    'eka1_rq31_exit_lane_right_open': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75, 3.75, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'open', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'exit', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 15,
    },
    'eka1_rq31_exit_lane_right': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75, 3.75, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'exit', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'end',
        'road_split_lane_idx': 12,
    },
    'eka1_rq31_exit_right_continuation_begin_end': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'solid'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white'],
        'road_split_type': 'none',
        'road_split_lane_idx': 11,
    },
    'eka1_rq31_exit_right_continuation_shoulder_begin': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'start',
        'road_split_lane_idx': 14,
    },
    'eka1_rq31_exit_right_continuation_shoulder_end': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'end',
        'road_split_lane_idx': 14,
    },
    'eka1_rq31_entry_right': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75, 3.75, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'exit', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'start',
        'road_split_lane_idx': 12,
    },
    'eka1_rq31_entry_right_close': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 3.75, 3.75, 0.75, 2.0, 0.0, 2.0, 0.75, 3.75, 3.75, 3.75, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'close', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'exit', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'bold', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.30, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 15,
    },
    'eka1_rq36': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [1.5, 2.5, 0.5, 3.75, 3.5, 3.5, 0.75, 2.0, 0.0, 2.0, 0.75, 3.5, 3.5, 3.75, 0.5, 2.5, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'driving', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'standard', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.15, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 16,
    },
    'eka1_rq43_5': {
        'sides': ['left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'left', 'center', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right', 'right'],
        'widths': [2.5, 2.5, 0.5, 3.75, 3.75, 3.5, 3.5, 0.75, 2.0, 0.0, 2.0, 0.75, 3.5, 3.5, 3.75, 3.75, 0.5, 2.5, 2.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'driving', 'driving', 'driving', 'driving', 'border', 'median', 'center', 'median', 'border', 'driving', 'driving', 'driving', 'driving', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'broken', 'broken', 'broken', 'solid', 'none', 'none', 'none', 'solid', 'broken', 'broken', 'broken', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'standard', 'standard', 'standard', 'bold', 'none', 'none', 'none', 'bold', 'standard', 'standard', 'standard', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.15, 0.15, 0.15, 0.30, 0.0, 0.0, 0.0, 0.30, 0.15, 0.15, 0.15, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'white', 'white', 'white', 'none', 'none', 'none', 'white', 'white', 'white', 'white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 18,
    },
    'on_ramp_end': {
        'sides': ['left', 'left', 'left', 'center', 'right'],
        'widths': [1.5, 3.0, 0.75, 0.0, 3.75],
        'widths_change': ['none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'center', 'offRamp'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'solid'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'bold'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.30],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white'],
        'road_split_type': 'none',
        'road_split_lane_idx': 4,
    },
    'on_ramp_shoulder_end': {
        'sides': ['left', 'left', 'left', 'center', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 0.0, 3.75, 0.75, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'center', 'offRamp', 'border', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'solid', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'bold', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.30, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'none', 'none'],
        'road_split_type': 'start',
        'road_split_lane_idx': 6,
    },
    'on_ramp': {
        'sides': ['left', 'left', 'left', 'center', 'right', 'right', 'right'],
        'widths': [1.5, 3.0, 0.75, 0.0, 3.75, 0.75, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'stop', 'border', 'center', 'offRamp', 'border', 'shoulder'],
        'road_mark_types': ['none', 'none', 'none', 'solid', 'solid', 'none', 'none'],
        'road_mark_weights': ['none', 'none', 'none', 'bold', 'bold', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.0, 0.30, 0.30, 0.0, 0.0],
        'road_mark_colors': ['none', 'none', 'none', 'white', 'white', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 6,
    },
    'off_ramp_begin': {
        'sides': ['left', 'center', 'right', 'right', 'right'],
        'widths': [3.75, 0.0, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none'],
        'types': ['offRamp', 'center', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['solid', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['bold', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.30, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 4,
    },
    'off_ramp_shoulder_begin': {
        'sides': ['left', 'left', 'left', 'center', 'right', 'right', 'right'],
        'widths': [1.5, 0.75, 3.75, 0.0, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'border', 'offRamp', 'center', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'solid', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none','bold', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.30, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none','white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'start',
        'road_split_lane_idx': 0,
    },
    'off_ramp': {
        'sides': ['left', 'left', 'left', 'center', 'right', 'right', 'right'],
        'widths': [1.5, 0.75, 3.75, 0.0, 0.75, 3.0, 1.5],
        'widths_change': ['none', 'none', 'none', 'none', 'none', 'none', 'none'],
        'types': ['shoulder', 'border', 'offRamp', 'center', 'border', 'stop', 'shoulder'],
        'road_mark_types': ['none', 'none', 'solid', 'solid', 'none', 'none', 'none'],
        'road_mark_weights': ['none', 'none','bold', 'bold', 'none', 'none', 'none'],
        'road_mark_widths': [0.0, 0.0, 0.30, 0.30, 0.0, 0.0, 0.0],
        'road_mark_colors': ['none', 'none','white', 'white', 'none', 'none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 6,
    },
    'shoulder_left': {
        'sides': ['left', 'center'],
        'widths': [1.5, 0.0],
        'widths_change': ['none', 'none'],
        'types': ['shoulder', 'center'],
        'road_mark_types': ['none', 'none'],
        'road_mark_weights': ['none', 'none'],
        'road_mark_widths': [0.0, 0.0],
        'road_mark_colors': ['none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 1,
    },
    'shoulder_right': {
        'sides': ['center', 'right'],
        'widths': [0.0, 1.5],
        'widths_change': ['none', 'none'],
        'types': ['center', 'shoulder'],
        'road_mark_types': ['none', 'none'],
        'road_mark_weights': ['none', 'none'],
        'road_mark_widths': [0.0, 0.0],
        'road_mark_colors': ['none', 'none'],
        'road_split_type': 'none',
        'road_split_lane_idx': 1,
    },
}
